### ISSUE TITLE
Add (secure) Tiller Installation, out-of-the-box

### ISSUE THREAD

**Issue by jhunt** [jhunt/k8s-boshrelease#13]
I would like to be able to optionally (and securely) install the bits and pieces necessary to make helm usable on a stock k8s cluster deployed by this BOSH release.

see https://blog.ropnop.com/attacking-default-installs-of-helm-on-kubernetes/

**Comment by drnic** [comment]
You can probably not do this now as helm 3 removes tiller.

Or try out https://github.com/starkandwayne/helm-tiller-manager

**Comment by jhunt** [comment]
Interesting, as of 4 days ago (per https://github.com/helm/helm/releases/tag/v3.0.0-beta.5), 3.0.0-rc1 is very close to release.  I think we'll close this and move on with the rest of the ecosystem.
