### ISSUE TITLE
Support KubeCF bits on 127.0.0.1:32123

### ISSUE THREAD

**Issue by cweibel** [jhunt/k8s-boshrelease#32]
Right now kubelet cannot pull images back from KubeCF blobstore since the service does not listen on loopback.

Adding "127.0.0.1/8" to the array of nodePortAddress in the kube-proxy [here](https://github.com/jhunt/k8s-boshrelease/blob/c742211e2e9f9fb4018bbfaa116c725128e75858/jobs/control/templates/k8s/kube-proxy.yml#L69) fixes this issue.

For example the following manual change results in a usable binding:

```
nodePortAddresses: ["10.128.57.192/28", "127.0.0.1/8"]
```

After making the change manually to the configmap and recreating the kube-proxy pods apps can successfully stage in KubeCF.

**Comment by jhunt** [comment]
If you add `127.0.0.1/8` (or the more restricted `127.0.0.1/32`) to the `network.nodes` list on the `control` job I think the the configMap will do what you want.

**Comment by jhunt** [comment]
I believe this is fixed.
