### ISSUE TITLE
Pod status Unknown after recreate

### ISSUE THREAD

**Issue by tpoland** [jhunt/k8s-boshrelease#33]
After running `bosh` with the `recreate` directive for single VM k8s cluster the coredns pods and any pods deployed outside of the `kube-system` namespace have a status of "Unknown". Describing the pod shows a Stats of "Running" with a Container state of "Terminated" and an Event message status of "Pod sandbox changed, it will be killed and re-created.".

Terminating the affected pods results in a recovery of those pods.

**Comment by tpoland** [comment]
Upgrading the bosh deployment from a 1-node to a 2-node cluster also resulted in the same pod set failing.

Using a two-node k8s cluster fewer pods end up in an "Unknown" state, but the issue is still present.

**Comment by tpoland** [comment]
Upgrading from a 2-node to 3-node k8s cluster does not result in any pod failures. Issuing a `recreate` does still result in a small subset of pod failures.

**Comment by jhunt** [comment]
Yeah, I think we need to start cordoning and draining nodes in a pre-stop.  Curious how that will effect tinynetes, and whether or not we'll have to make that configurable...

**Comment by jhunt** [comment]
I think this is handled in #34, with a drain script.  Take a look, and see what you think.

**Comment by jhunt** [comment]
The fixes in PR #34 will be available in the next (1.18.x) release.
