### ISSUE TITLE
blobs is private

### ISSUE THREAD

**Issue by obeyler** [jhunt/k8s-boshrelease#56]
Blob download 'containerd/containerd-1.3.5-linux-amd64.tar.gz' (id: 742cb1fa-2f84-4665-4d82-884886227d3c) failed

- Getting blob '742cb1fa-2f84-4665-4d82-884886227d3c' for path 'containerd/containerd-1.3.5-linux-amd64.tar.gz':
    Getting blob from inner blobstore:
      Getting blob from inner blobstore:
        AccessDenied: Access Denied
	status code: 403, request id: 784F91B43B9FA398, host id: EAfthPNGLY4THuXdcRqZMXe0Z7E1d2CBQNyBSAJw08wC2BI+oRqfhpQnOVklB2hyduZ3TSIAMko=

**Comment by jhunt** [comment]
I re-chacled all the blobs in the bucket, and set the following default bucket policy:

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AddPerm",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::k8s-boshrelease/*"
        }
    ]
}
```

which should prevent this from happening in the future.
